### ISSUE TITLE
Angular Support?

### ISSUE THREAD

**Issue by ScottMGerstl** [moayadnajd/nativescript-fontawesome#1]
Do you have any plans to make a similar version for nativescript-angular? I really like the idea of bootstrapping it at the main/app level instead of in every module and submodule like nativescript-ngx-fonticon

Thanks!

**Comment by moayadnajd** [comment]
@ScottMGerstl  i have a busy month but yes i will add angular support soon

**Comment by yalva** [comment]
Do you still have this on your radar?

**Comment by moayadnajd** [comment]
@ScottMGerstl @yalva no not now in iOS not working need a lot of work  just use fonticon for now
