### ISSUE TITLE
Fontawesome.init() not a function

### ISSUE THREAD

**Issue by devyaz** [moayadnajd/nativescript-fontawesome#2]
i instaled in a JS App in my app.js `Fontawesome.init();
` says its not a function

**Comment by moayadnajd** [comment]
@devyaz can you provide example repo

**Comment by devyaz** [comment]
this is a typescript that your example code requires
`import { Fontawesome } from 'nativescript-fontawesome';
Fontawesome.init();
`
but am using vanilla Javascript so it goes
`const  Fontawesome= require("nativescript-fontawesome"');
Fontawesome.init();//here is the problem!!
`

**Comment by moayadnajd** [comment]
@devyaz 

i copped what type script generate try use this and let me know 
```
var nativescript_fontawesome_1 = require("nativescript-fontawesome");
nativescript_fontawesome_1.Fontawesome.init();
```

**Comment by devyaz** [comment]
@moayadnajd  sorry for late response, but after using the code you suggested, it now runs without error but nothing is displayed!! here's my app.js
````
var application = require("application");
var nativescript_fontawesome_1 = require("nativescript-fontawesome");
nativescript_fontawesome_1.Fontawesome.init();
var frame = require('ui/frame');
if (application.android) {
    application.android.on(application.AndroidApplication.activityBackPressedEvent, backEvent);
}
function backEvent(args) {
    var currentPage = frame.topmost().currentPage;
    if (currentPage && currentPage.exports && typeof currentPage.exports.backEvent === "function") {
         currentPage.exports.backEvent(args);
   }
}

application.start({ moduleName: "home" });
````
and xml in home.xml
`<Label class="ion" text="&#xf203;" fontSize="28"></Label>//this shows map icon
<Label class="fa" text="{{'fa-bluetooth' | fontawesome }}"></Label> //this is blank but displays unicoded fonts OK
`
app.css
`.fa {
  font-family: "FontAwesome";
}
.ion{
  font-family: "ionicons";
}
`
fonticon is installed and if i use unicoded fonts , it displays properly

**Comment by moayadnajd** [comment]
@devyaz  did you download the fonts files ? and put them in the fonts folder ?

**Comment by moayadnajd** [comment]
@devyaz can you send me your code or send me example so i can take a look

**Comment by devyaz** [comment]
yes thats why i said it can display only unicode but not by font name

On Tue, Nov 21, 2017 at 3:24 PM, Moayad Al-Najdawi <notifications@github.com

**Comment by devyaz** [comment]
this is my app.js
````
var application = require("application");
var nativescript_fontawesome_1 = require("nativescript-fontawesome");
nativescript_fontawesome_1.Fontawesome.init();
var frame = require('ui/frame');
if (application.android) {
    application.android.on(application.AndroidApplication.activityBackPressedEvent, backEvent);
}
function backEvent(args) {
    var currentPage = frame.topmost().currentPage;
    if (currentPage && currentPage.exports && typeof currentPage.exports.backEvent === "function") {
         currentPage.exports.backEvent(args);
   }
}

application.start({ moduleName: "home" });
````

**Comment by devyaz** [comment]
`
 <Label class="fa" text="{{'fa-bluetooth' | fontawesome }}"></Label> `

**Comment by devyaz** [comment]
*CSS*
````
.fa { font-family: "FontAwesome"; }

 .ion{ font-family: "ionicons"; }

**Comment by moayadnajd** [comment]
@devyaz are you using iOS or android ?

try this css for iOS need actual font name 

```
.fa {
    font-family: FontAwesome, fontawesome-webfont;
}
```

**Comment by devyaz** [comment]
am on android, and my font name is _FontAwesome_  i renamed it fromfontawesome-webfont  which should work for both IOS and Android
