### ISSUE TITLE
icon with test

### ISSUE THREAD

**Issue by LorenDorez** [moayadnajd/nativescript-fontawesome#3]
when i try this 
```
<Button text="{{'fa-sign-in' | fontawesome}} Sign In" class="fa btn btn-primary btn-md" tap="signIn" />
```
it just renders it all as text. If i remove the "Sign In" it works as expected

**Comment by moayadnajd** [comment]
Try this 
`<Button text="{{ fontawesome('fa-sign-in') + ' Sign In' }}" class="fa btn-primary" tap="signIn" />`
